//add here most rarely modified headers to speed up debug build compilation
#include "WorldSocket.h"                                    // must be first to make ACE happy with ACE includes in it
#include "Common.h"

#include "AccountMgr.h"
// #include "ArenaTeam.h"
// #include "ArenaTeamMgr.h"
#include "BattleGround.h"
#include "BattleGroundAB.h"
#include "BattleGroundAV.h"
#include "BattleGroundWS.h"
// #include "BattleGroundIC.h"
// #include "BattleGroundSA.h"
// #include "CellImpl.h"
#include "Chat.h"
// #include "ChatTextBuilder.h"
// #include "Common.h"
// #include "Database/DatabaseEnv.h"
// #include "Database/QueryResult.h"
// #include "DBCEnums.h"
// #include "DBCStores.h"
// #include "DisableMgr.h"
// #include "GameEventMgr.h"
// #include "GridNotifiersImpl.h"
// #include "Guild.h"
#include "GuildMgr.h"
#include "Guild.h"
// #include "InstanceScript.h"
// #include "Language.h"
// #include "Map.h"
// #include "MapManager.h"
// #include "ItemPrototype.h"
#include "ObjectMgr.h"
// #include "Player.h"
// #include "ReputationMgr.h"
// #include "World.h"
// #include "WorldPacket.h"
#include "SpellMgr.h"
#include "GameEventMgr.h"
#include "World.h"

#include "src/AchievementMgr.h"
#include "src/AchievementScriptMgr.h"